apiVersion: v1
data:
  clusterissuer: "false"
  domain: 23.251.135.97.nip.io
  email: ""
  exposer: Ingress
  issuer: ""
  tls: "false"
  urltemplate: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-config
